# Importing python libraries to be used

In [1]:
import pandas as pd
import numpy as np

# Loading datasets to be used
Add more datasets as needed

In [10]:
# Loading TFT datasets
TFT_C_Data_df = pd.read_csv("Datasets\TFT_Match_Data\TFT_Challenger_MatchData.csv")
TFT_D_Data_df = pd.read_csv("Datasets\TFT_Match_Data\TFT_Diamond_MatchData.csv")
TFT_GM_Data_df = pd.read_csv("Datasets\TFT_Match_Data\TFT_GrandMaster_MatchData.csv")
TFT_M_Data_df = pd.read_csv("Datasets\TFT_Match_Data\TFT_Master_MatchData.csv")
TFT_P_Data_df = pd.read_csv("Datasets\TFT_Match_Data\TFT_Platinum_MatchData.csv")

In [51]:
# Loading PUBG datasets 
PUBG_death1_df = pd.read_csv("Datasets\PUBG_Match_Data\deaths\kill_match_stats_final_0.csv")
PUBG_death2_df = pd.read_csv("Datasets\PUBG_Match_Data\deaths\kill_match_stats_final_1.csv")
PUBG_death3_df = pd.read_csv("Datasets\PUBG_Match_Data\deaths\kill_match_stats_final_2.csv")
PUBG_death4_df = pd.read_csv("Datasets\PUBG_Match_Data\deaths\kill_match_stats_final_3.csv")
PUBG_death5_df = pd.read_csv("Datasets\PUBG_Match_Data\deaths\kill_match_stats_final_4.csv")
PUBG_agg_stats_df = pd.read_csv("Datasets\\PUBG_Match_Data\\aggregate\\agg_match_stats_4.csv")

In [47]:
# Loading CSGO datasets
CSGO_M_DMG1_df = pd.read_csv("Datasets\CSGO_Match_Data\esea_master_dmg_demos.part1.csv")
CSGO_M_DMG2_df = pd.read_csv("Datasets\CSGO_Match_Data\esea_master_dmg_demos.part2.csv")
CSGO_M_GRE1_df = pd.read_csv("Datasets\CSGO_Match_Data\esea_master_grenades_demos.part1.csv")
CSGO_M_GRE2_df = pd.read_csv("Datasets\CSGO_Match_Data\esea_master_grenades_demos.part2.csv")
CSGO_M_Kills1_df = pd.read_csv("Datasets\CSGO_Match_Data\esea_master_kills_demos.part1.csv")
CSGO_M_Kills2_df = pd.read_csv("Datasets\CSGO_Match_Data\esea_master_kills_demos.part2.csv")
CSGO_Meta_1_df = pd.read_csv("Datasets\CSGO_Match_Data\esea_meta_demos.part1.csv")
CSGO_Meta_2_df = pd.read_csv("Datasets\CSGO_Match_Data\esea_meta_demos.part2.csv")
CSGO_Map_df = pd.read_csv("Datasets\CSGO_Match_Data\map_data.csv")
CSGO_MM_Grenades = pd.read_csv("Datasets\CSGO_Match_Data\mm_grenades_demos.csv")
CSGO_MM_Master = pd.read_csv("Datasets\CSGO_Match_Data\mm_master_demos.csv")

# Data Preprocessing

In [3]:
TFT_C_Data_df = TFT_C_Data_df.drop(columns=['gameId','gameDuration'])
TFT_D_Data_df = TFT_D_Data_df.drop(columns=['gameId','gameDuration'])
TFT_GM_Data_df = TFT_GM_Data_df.drop(columns=['gameId','gameDuration'])
TFT_M_Data_df = TFT_M_Data_df.drop(columns=['gameId','gameDuration'])
TFT_P_Data_df = TFT_P_Data_df.drop(columns=['gameId','gameDuration'])

In [ ]:
# View dataset info
CSGO_M_DMG1_df.head()

,file,round,tick,seconds,att_team,vic_team,att_side,vic_side,hp_dmg,arm_dmg,...,wp,wp_type,att_id,att_rank,vic_id,vic_rank,att_pos_x,att_pos_y,vic_pos_x,vic_pos_y
0,esea_match_13770997.dem,1,14372,111.8476,World,Animal Style,NaN,CounterTerrorist,1,0,...,Unknown,Unkown,0,0,76561198055054795,0,0.0000,0.00000,0.0000,0.000000
1,esea_match_13770997.dem,1,15972,124.3761,Animal Style,Hentai Hooligans,CounterTerrorist,Terrorist,18,9,...,USP,Pistol,76561198048742997,0,76561198082200410,0,-1499.6900,63.33829,-669.5558,-79.769570
2,esea_match_13770997.dem,1,16058,125.0495,Animal Style,Hentai Hooligans,CounterTerrorist,Terrorist,100,0,...,USP,Pistol,76561198055054795,0,76561197961009213,0,-1066.8740,3.44563,-614.1868,-91.707770
3,esea_match_13770997.dem,1,16066,125.1121,Hentai Hooligans,Animal Style,Terrorist,CounterTerrorist,12,7,...,Glock,Pistol,76561198082200410,0,76561198055054795,0,-747.3146,-49.32681,-1065.5560,9.381622
4,esea_match_13770997.dem,1,16108,125.4410,Animal Style,Hentai Hooligans,CounterTerrorist,Terrorist,15,7,...,USP,Pistol,76561198048742997,0,76561198082200410,0,-1501.8610,49.19798,-748.4188,-53.469220

In [49]:
# Check for any null values in the data
CSGO_M_DMG1_df.isnull().any()

file               False
round              False
tick               False
seconds             True
att_team           False
vic_team           False
att_side            True
vic_side           False
hp_dmg             False
arm_dmg            False
is_bomb_planted    False
bomb_site           True
hitbox             False
wp                 False
wp_type            False
att_id             False
att_rank           False
vic_id             False
vic_rank           False
att_pos_x          False
att_pos_y          False
vic_pos_x          False
vic_pos_y          False
dtype: bool

As shown here, att_side, seconds and bomb_site have null values

In [50]:
# Looking at the dataset, att_side and vic_side should have Terrorist and CounterTerrorist in both columns. So, we can do categorical imputation with a function to classify them.
# Imputation for att_side
def impute_att_side(cols):
    att_side = cols[0]
    vic_side = cols[1]
    if pd.isnull(att_side):
       if vic_side == 'CounterTerrorist':
           return 'Terrorist'
       else:
           return 'CounterTerrorist'
    else:
        return att_side

CSGO_M_DMG1_df["att_side"] = CSGO_M_DMG1_df.loc[:, ["att_side", "vic_side"]].apply(impute_att_side, axis = 1)

C:\Users\Perez\AppData\Local\Temp\ipykernel_29992\3502958027.py:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  att_side = cols[0]
C:\Users\Perez\AppData\Local\Temp\ipykernel_29992\3502958027.py:5: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  vic_side = cols[1]

In [53]:
CSGO_M_DMG1_df.isnull().sum()

file                     0
round                    0
tick                     0
seconds                515
att_team                 0
vic_team                 0
att_side                 0
vic_side                 0
hp_dmg                   0
arm_dmg                  0
is_bomb_planted          0
bomb_site          5129343
hitbox                   0
wp                       0
wp_type                  0
att_id                   0
att_rank                 0
vic_id                   0
vic_rank                 0
att_pos_x                0
att_pos_y                0
vic_pos_x                0
vic_pos_y                0
dtype: int64

In [56]:
# We decide to drop the null values for seconds as it is very small in comparison with the total observations listed here
CSGO_M_DMG1_df = CSGO_M_DMG1_df.dropna(subset="seconds")
CSGO_M_DMG1_df.isnull().sum()

file                     0
round                    0
tick                     0
seconds                  0
att_team                 0
vic_team                 0
att_side                 0
vic_side                 0
hp_dmg                   0
arm_dmg                  0
is_bomb_planted          0
bomb_site          5128875
hitbox                   0
wp                       0
wp_type                  0
att_id                   0
att_rank                 0
vic_id                   0
vic_rank                 0
att_pos_x                0
att_pos_y                0
vic_pos_x                0
vic_pos_y                0
dtype: int64

In [57]:
# However for the bomb site, we drop the column since it has a lot of missing values
CSGO_M_DMG1_df.drop('bomb_site', axis = 1, inplace = True)
CSGO_M_DMG1_df.isnull().sum()

file               0
round              0
tick               0
seconds            0
att_team           0
vic_team           0
att_side           0
vic_side           0
hp_dmg             0
arm_dmg            0
is_bomb_planted    0
hitbox             0
wp                 0
wp_type            0
att_id             0
att_rank           0
vic_id             0
vic_rank           0
att_pos_x          0
att_pos_y          0
vic_pos_x          0
vic_pos_y          0
dtype: int64

In [ ]:
CSGO_M_DMG2_df.head(20)

,file,round,tick,seconds,att_team,vic_team,att_side,vic_side,hp_dmg,arm_dmg,...,wp,wp_type,att_id,att_rank,vic_id,vic_rank,att_pos_x,att_pos_y,vic_pos_x,vic_pos_y
0,esea_match_13818366.dem,1,21257,165.8779,Team 2,Team 1,Terrorist,CounterTerrorist,20,0,...,Glock,Pistol,76561198242409332,0,76561198323654039,0,695.9623,1459.5790,-299.9824,2220.1480
1,esea_match_13818366.dem,1,21653,168.9752,Team 1,Team 2,CounterTerrorist,Terrorist,100,0,...,USP,Pistol,76561198013283167,0,76561198355844440,0,-236.3433,923.7209,271.5201,2097.4790
2,esea_match_13818366.dem,1,21717,169.4758,Team 1,Team 2,CounterTerrorist,Terrorist,100,0,...,USP,Pistol,76561198323654039,0,76561198305399476,0,-422.4744,2051.0920,909.0534,1543.7200
3,esea_match_13818366.dem,1,21937,171.1965,Team 1,Team 2,CounterTerrorist,Terrorist,14,6,...,USP,Pistol,76561198323654039,0,76561197962070685,0,-263.6333,2248.5440,704.7518,1579.3470
4,esea_match_13818366.dem,1,22229,173.4804,Team 1,Team 2,CounterTerrorist,Terrorist,100,0,...,USP,Pistol,76561198853893462,0,76561198397252030,0,-558.0109,-874.1711,254.4920,-691.1022
5,esea_match_13818366.dem,1,22565,176.1084,Team 1,Team 2,CounterTerrorist,Terrorist,14,7,...,USP,Pistol,76561198323654039,0,76561197962070685,0,-257.3235,2237.7820,565.4832,1591.9950
6,esea_match_13818366.dem,1,22653,176.7967,Team 2,Team 1,Terrorist,CounterTerrorist,8,4,...,Glock,Pistol,76561198242409332,0,76561198186753298,0,721.1249,1737.9440,-683.3134,1264.1540
7,esea_match_13818366.dem,1,22711,177.2503,Team 2,Team 1,Terrorist,CounterTerrorist,8,4,...,Glock,Pistol,76561198242409332,0,76561198186753298,0,694.5822,1815.2100,-685.8182,1271.3080
8,esea_match_13818366.dem,1,22807,178.0012,Team 1,Team 2,CounterTerrorist,Terrorist,13,6,...,USP,Pistol,76561198186753298,0,76561198242409332,0,-681.6322,1259.1700,672.0367,1854.8990
9,esea_match_13818366.dem,1,24575,191.8296,Team 1,Team 2,CounterTerrorist,Terrorist,2,1,...,USP,Pistol,76561198323654039,0,76561198242409332,0,212.5068,1298.0160,554.1100,1945.2070
10,esea_match_13818366.dem,1,24861,194.0665,Team 2,Team 1,Terrorist,CounterTerrorist,24,0,...,Glock,Pistol,76561198242409332,0,76561198323654039,0,560.3470,1935.8380,338.3871,1353.7320
11,esea_match_13818366.dem,1,24985,195.0364,Team 1,Team 2,CounterTerrorist,Terrorist,15,7,...,USP,Pistol,76561198323654039,0,76561198242409332,0,327.8214,1377.7860,561.9266,1937.9930
12,esea_match_13818366.dem,1,25019,195.3023,Team 1,Team 2,CounterTerrorist,Terrorist,70,0,...,USP,Pistol,76561198323654039,0,76561198242409332,0,310.7552,1377.0320,559.7442,1938.7750
13,esea_match_13818366.dem,1,25347,197.8677,Team 1,Team 2,CounterTerrorist,Terrorist,17,8,...,USP,Pistol,76561198186753298,0,76561197962070685,0,235.2591,2140.3440,426.8561,2087.5550
14,esea_match_13818366.dem,1,25355,197.9303,Team 2,Team 1,Terrorist,CounterTerrorist,13,7,...,Glock,Pistol,76561197962070685,0,76561198186753298,0,426.2978,2093.5620,234.7218,2138.9470
15,esea_match_13818366.dem,1,25375,198.0867,Team 2,Team 1,Terrorist,CounterTerrorist,13,7,...,Glock,Pistol,76561197962070685,0,76561198186753298,0,428.9287,2111.5150,238.0826,2148.7850
16,esea_match_13818366.dem,1,25381,198.1337,Team 1,Team 2,CounterTerrorist,Terrorist,17,8,...,USP,Pistol,76561198186753298,0,76561197962070685,0,239.1910,2152.1600,429.8139,2116.1470
17,esea_match_13818366.dem,1,25415,198.3996,Team 2,Team 1,Terrorist,CounterTerrorist,13,7,...,Glock,Pistol,76561197962070685,0,76561198186753298,0,431.1750,2135.6880,244.6946,2170.4800
18,esea_match_13818366.dem,1,25435,198.5560,Team 2,Team 1,Terrorist,CounterTerrorist,13,7,...,Glock,Pistol,76561197962070685,0,76561198186753298,0,432.2860,2150.5810,242.5676,2163.0030
19,esea_match_13818366.dem,1,25439,198.5873,Team 1,Team 2,CounterTerrorist,Terrorist,17,8,...,USP,Pistol,76561198186753298,0,76561197962070685,0,242.1210,2161.1160,432.6137,2153.8330

In [64]:
CSGO_M_DMG2_df.isnull().any()

file               False
round              False
tick               False
seconds             True
att_team           False
vic_team           False
att_side            True
vic_side           False
hp_dmg             False
arm_dmg            False
is_bomb_planted    False
bomb_site           True
hitbox             False
wp                 False
wp_type            False
att_id             False
att_rank           False
vic_id             False
vic_rank           False
att_pos_x          False
att_pos_y          False
vic_pos_x          False
vic_pos_y          False
dtype: bool

In [65]:
def impute_att_side(cols):
    att_side = cols[0]
    vic_side = cols[1]
    if pd.isnull(att_side):
       if vic_side == 'CounterTerrorist':
           return 'Terrorist'
       else:
           return 'CounterTerrorist'
    else:
        return att_side

CSGO_M_DMG2_df["att_side"] = CSGO_M_DMG2_df.loc[:, ["att_side", "vic_side"]].apply(impute_att_side, axis = 1)
CSGO_M_DMG2_df.isnull().any()

C:\Users\Perez\AppData\Local\Temp\ipykernel_29992\855319145.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  att_side = cols[0]
C:\Users\Perez\AppData\Local\Temp\ipykernel_29992\855319145.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  vic_side = cols[1]

file               False
round              False
tick               False
seconds             True
att_team           False
vic_team           False
att_side           False
vic_side           False
hp_dmg             False
arm_dmg            False
is_bomb_planted    False
bomb_site           True
hitbox             False
wp                 False
wp_type            False
att_id             False
att_rank           False
vic_id             False
vic_rank           False
att_pos_x          False
att_pos_y          False
vic_pos_x          False
vic_pos_y          False
dtype: bool

In [66]:
CSGO_M_DMG2_df = CSGO_M_DMG2_df.dropna(subset="seconds")
CSGO_M_DMG2_df.isnull().sum()

file                     0
round                    0
tick                     0
seconds                  0
att_team                 0
vic_team                 0
att_side                 0
vic_side                 0
hp_dmg                   0
arm_dmg                  0
is_bomb_planted          0
bomb_site          3888851
hitbox                   0
wp                       0
wp_type                  0
att_id                   0
att_rank                 0
vic_id                   0
vic_rank                 0
att_pos_x                0
att_pos_y                0
vic_pos_x                0
vic_pos_y                0
dtype: int64

In [67]:
CSGO_M_DMG2_df.drop('bomb_site', axis = 1, inplace = True)
CSGO_M_DMG2_df.isnull().sum()

file               0
round              0
tick               0
seconds            0
att_team           0
vic_team           0
att_side           0
vic_side           0
hp_dmg             0
arm_dmg            0
is_bomb_planted    0
hitbox             0
wp                 0
wp_type            0
att_id             0
att_rank           0
vic_id             0
vic_rank           0
att_pos_x          0
att_pos_y          0
vic_pos_x          0
vic_pos_y          0
dtype: int64

# Exploratory Data Analysis